INSERT INTO `class` VALUES ('Alchemist'),
                            ('Artificer'),
                            ('Barbarian'),
                            ('Bard'),
                            ('Captain'),
                            ('Cleric'),
                            ('Druid'),
                            ('Fighter'),
                            ('Gunslinger'),
                            ('Monk'),
                            ('Paladin'),
                            ('Ranger'),
                            ('Rogue'),
                            ('Sorcerer'),
                            ('Warden'),
                            ('Warlock'),
                            ('Wizard');